const state={events:[],stats:null,currentView:'overview',filter:'all',query:'',selected:null,graph:{nodes:[],links:[],running:true,scale:1,offsetX:0,offsetY:0,drag:null,pan:null,raf:null}};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n||0);
async function boot(){try{const r=await fetch('./data/events.json');const d=await r.json();state.events=d.events;state.stats=d.stats;renderAll()}catch(e){$('.graph-stage').innerHTML='<div class="empty">无法载入索引，请在项目根目录启动 web server。</div>'}}
function renderAll(){renderMetrics();renderLegend();renderGraph();renderSignals();renderRecent();renderFilters();renderEvents();renderInsights()}
function renderMetrics(){const s=state.stats;$('#metrics').innerHTML=[['事件总数',fmt(s.events),'FULL COVERAGE'],['图谱节点',fmt(s.nodes),'ENTITY LAYER'],['知识关系',fmt(s.edges),'RELATION LAYER'],['证据文档',fmt(s.documents),'SOURCE LAYER']].map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value">${x[1]}</div><div class="metric-accent">${x[2]}</div></div>`).join('')}
function renderLegend(){const colors=['#ff836d','#72d4d0','#c7ef68','#f4c96b'];const types=Object.entries(state.stats.types).slice(0,4);$('#legend').innerHTML=types.map((x,i)=>`<span><i style="background:${colors[i]}"></i>${x[0]}</span>`).join('')}
function renderGraph(){const data=state.events.slice(0,38),stage=$('#graph-stage'),w=900,h=420;const colors=['#ff836d','#72d4d0','#c7ef68','#f4c96b'];const nodes=data.map((e,i)=>({e,x:w/2+Math.cos(i*2.399)*(90+(i%5)*40),y:h/2+Math.sin(i*2.399)*(65+(i%4)*34),vx:0,vy:0,r:i<8?9:6}));const links=nodes.slice(1).map((n,i)=>({a:n,b:nodes[(i+3)%nodes.length]}));state.graph.nodes=nodes;state.graph.links=links;state.graph.scale=1;state.graph.offsetX=0;state.graph.offsetY=0;stage.querySelector('svg')?.remove();const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.innerHTML='<g class="graph-world"><g class="graph-edges"></g><g class="graph-nodes"></g></g>';stage.appendChild(svg);nodes.forEach((n,i)=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('graph-node');g.dataset.id=n.e.id;g.innerHTML=`<circle r="${n.r}" fill="${colors[i%4]}"/><text x="13" y="4">${esc(n.e.title.slice(0,18))}</text>`;g.addEventListener('click',ev=>{ev.stopPropagation();selectGraphNode(n)});g.addEventListener('pointerdown',ev=>startNodeDrag(ev,n,g));g.addEventListener('pointerenter',()=>showGraphTooltip(n,stage));g.addEventListener('pointerleave',hideGraphTooltip);$('.graph-nodes').appendChild(g)});stage.querySelector('.graph-edges').innerHTML=links.map(l=>`<line class="edge"/>`).join('');stage.addEventListener('wheel',graphZoom,{passive:false});stage.addEventListener('pointerdown',startGraphPan);stage.addEventListener('pointermove',moveGraphPan);stage.addEventListener('pointerup',endGraphPan);stage.addEventListener('pointerleave',endGraphPan);$('#graph-reset').onclick=()=>renderGraph();$('#graph-pause').onclick=()=>{state.graph.running=!state.graph.running;$('#graph-pause').textContent=state.graph.running?'暂停':'继续';if(state.graph.running)animateGraph()};$('#graph-fit').onclick=()=>{state.graph.scale=1;state.graph.offsetX=0;state.graph.offsetY=0;renderGraph()};animateGraph()}
function animateGraph(){if(!state.graph.running)return;const g=state.graph,nodes=g.nodes;for(const n of nodes){n.vx+=(450-n.x)*.0005;n.vy+=(210-n.y)*.0005;n.vx*=.985;n.vy*=.985;n.x+=n.vx;n.y+=n.vy;for(const other of nodes){if(n===other)continue;const dx=n.x-other.x,dy=n.y-other.y,d= Math.max(30,Math.hypot(dx,dy));if(d<135){n.vx+=dx/d*(135-d)*.002;n.vy+=dy/d*(135-d)*.002}}}drawGraph();state.graph.raf=requestAnimationFrame(animateGraph)}
function drawGraph(){const g=state.graph;g.nodes.forEach((n,i)=>{const el=document.querySelector(`.graph-node[data-id="${CSS.escape(n.e.id)}"]`);if(el)el.setAttribute('transform',`translate(${n.x},${n.y})`)});document.querySelectorAll('.edge').forEach((el,i)=>{const l=g.links[i];el.setAttribute('x1',l.a.x);el.setAttribute('y1',l.a.y);el.setAttribute('x2',l.b.x);el.setAttribute('y2',l.b.y)});document.querySelector('.graph-world')?.setAttribute('transform',`translate(${g.offsetX} ${g.offsetY}) scale(${g.scale})`)}
function selectGraphNode(node){state.selected=node.e.id;const neighbors=new Set(state.graph.links.flatMap(l=>l.a===node?[l.b.e.id]:l.b===node?[l.a.e.id]:[]));document.querySelectorAll('.graph-node').forEach(el=>el.classList.toggle('dimmed',el.dataset.id!==node.e.id&&!neighbors.has(el.dataset.id)));document.querySelectorAll('.edge').forEach((el,i)=>{const l=state.graph.links[i];el.classList.toggle('highlighted',l.a===node||l.b===node)});openEvent(node.e.id)}
function startNodeDrag(ev,node,el){ev.stopPropagation();state.graph.drag={node,el};el.setPointerCapture(ev.pointerId);state.graph.running=false}
function startGraphPan(ev){if(ev.target.closest('.graph-node'))return;state.graph.pan={x:ev.clientX,y:ev.clientY,ox:state.graph.offsetX,oy:state.graph.offsetY}}
function moveGraphPan(ev){const g=state.graph;if(g.drag){const rect=$('#graph-stage').getBoundingClientRect();g.drag.node.x=(ev.clientX-rect.left)/rect.width*900;g.drag.node.y=(ev.clientY-rect.top)/rect.height*420;drawGraph()}else if(g.pan){g.offsetX=g.pan.ox+ev.clientX-g.pan.x;g.offsetY=g.pan.oy+ev.clientY-g.pan.y;drawGraph()}}
function endGraphPan(){state.graph.drag=null;state.graph.pan=null}
function graphZoom(ev){ev.preventDefault();state.graph.scale=Math.min(2.2,Math.max(.65,state.graph.scale+(ev.deltaY<0?.1:-.1)));drawGraph()}
function showGraphTooltip(node,stage){const tip=$('#graph-tooltip');tip.innerHTML=`<strong>${esc(node.e.title)}</strong><span>${node.e.id} · ${node.e.nodes} nodes · ${node.e.edges} edges</span>`;tip.classList.add('visible')}
function hideGraphTooltip(){$('#graph-tooltip').classList.remove('visible')}
function renderSignals(){const top=state.events.slice().sort((a,b)=>b.nodes-a.nodes).slice(0,4);$('#insight-list').innerHTML=top.map((e,i)=>`<div class="signal"><div class="signal-top"><span>TOP ${String(i+1).padStart(2,'0')} / ${e.id}</span><span>${e.reports} reports</span></div><strong>${esc(e.title)}</strong><p>${e.nodes} entities · ${e.edges} relations · ${esc(e.risk||'AI risk incident')}</p><div class="bar"><i style="width:${Math.min(96,35+e.nodes/3)}%"></i></div></div>`).join('')}
function renderRecent(){const rows=state.events.slice().sort((a,b)=>b.id.localeCompare(a.id,undefined,{numeric:true})).slice(0,6);$('#recent-events').innerHTML=`<table class="event-table"><thead><tr><th>EVENT</th><th>RISK PROFILE</th><th>REPORTS</th><th>GRAPH</th></tr></thead><tbody>${rows.map(e=>`<tr><td><span class="event-link" data-id="${e.id}">${esc(e.title)}</span><div class="event-id">${e.id}</div></td><td><span class="pill">${esc(e.risk||'Risk')}</span></td><td>${e.reports}</td><td>${e.nodes}N / ${e.edges}E</td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('.event-link').forEach(n=>n.onclick=()=>openEvent(n.dataset.id))}
function renderFilters(){const types=['all',...Object.keys(state.stats.types).slice(0,5)];$('#type-filters').innerHTML=types.map(t=>`<button class="filter ${t===state.filter?'active':''}" data-filter="${t}">${t==='all'?'全部事件':t}</button>`).join('');document.querySelectorAll('.filter').forEach(n=>n.onclick=()=>{state.filter=n.dataset.filter;renderFilters();renderEvents()})}
function filtered(){return state.events.filter(e=>(state.filter==='all'||e.riskType===state.filter)&&(!state.query||(e.title+e.id+e.risk).toLowerCase().includes(state.query.toLowerCase())))}
function renderEvents(){const list=filtered();$('#result-count').textContent=`${fmt(list.length)} 个事件`;$('#event-grid').innerHTML=list.slice(0,120).map(e=>`<article class="event-card" data-id="${e.id}"><div class="id">${e.id} / ${e.date||'UNKNOWN DATE'}</div><h3>${esc(e.title)}</h3><div class="event-meta"><span>${e.nodes} nodes</span><span>${e.edges} edges</span><span>${e.reports} sources</span></div></article>`).join('')||'<div class="empty">没有匹配的事件。</div>';document.querySelectorAll('.event-card').forEach(n=>n.onclick=()=>openEvent(n.dataset.id))}
function renderInsights(){const entries=Object.entries(state.stats.types);const max=Math.max(...entries.map(x=>x[1]));$('#type-chart').innerHTML=entries.slice(0,12).map(x=>`<div class="chart-row"><label>${x[0]}</label><div class="chart-bar"><i style="width:${x[1]/max*100}%"></i></div><b>${fmt(x[1])}</b></div>`).join('');const chains=state.stats.chains;$('#chain-stats').innerHTML=[['RiskSource → Risk',chains.risk],['Risk → Consequence',chains.consequence],['Consequence → Impact',chains.impact],['RiskControl → Risk',chains.control]].map(x=>`<div class="chain-item"><span>${x[0]}</span><b>${fmt(x[1])}</b></div>`).join('')}
const TYPE_COLORS={'AIRiskIncident':'#ff836d','AISystem':'#72d4d0','AIModel':'#5fb8b4','GPAIModel':'#3a9d99','AITechnique':'#8fd0c9','AICapability':'#a3d9d2','AIComponent':'#6bc4be','Data':'#9bc8e8','Stakeholder':'#c7ef68','AIDeveloper':'#b8e05a','AIProvider':'#a5d04d','AIDeployer':'#92bd3a','AIUser':'#7fa82e','Regulator':'#d4a0e8','AffectedActor':'#ff6b9d','RiskSource':'#ff836d','Risk':'#ff6b4a','Hazard':'#e85d3a','Threat':'#d04a2e','Vulnerability':'#ff9d7a','Consequence':'#ffa54d','Impact':'#f4c96b','RiskControl':'#7dd87d','Regulation':'#d4a0e8','Standard':'#c990e0','Obligation':'#b87dd4','NewsReport':'#6a8a9a','InformationSource':'#5a7a8a','Evidence':'#4a6a7a','KnowledgeStatement':'#3a5a6a','RoleAssignment':'#8a9a6a','Purpose':'#aab050','AILifecyclePhase':'#90a060','Domain':'#809050','Trend':'#708040'};
function typeColor(t){return TYPE_COLORS[t]||'#888'}
async function openEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;$('#drawer-content').innerHTML=`<span class="drawer-id">${e.id}</span><h2>${esc(e.title)}</h2><div class="drawer-section"><h4>EVENT PROFILE</h4><div class="detail-row"><span>报告数</span><b>${e.reports}</b></div><div class="detail-row"><span>节点 / 关系</span><b>${e.nodes} / ${e.edges}</b></div><div class="detail-row"><span>风险类别</span><b>${esc(e.risk||'AI Risk')}</b></div></div><div class="drawer-section" id="event-detail"><div class="empty">正在载入事件图谱…</div></div>`;$('#drawer').classList.add('open');$('#drawer-backdrop').classList.add('open');try{const d=await (await fetch(`../output/${id}/event_subgraph.json`)).json();const allNodes=d.nodes||[];const allEdges=d.edges||[];const risk=allNodes.filter(n=>['RiskSource','Risk','Hazard','Threat','Vulnerability','Consequence','Impact','RiskControl'].includes(n.entity_type));const ev=allNodes.flatMap(n=>n.evidence||[]).slice(0,5);$('#event-detail').innerHTML=`<div class="drawer-section"><h4>EVENT GRAPH</h4><div class="event-graph-toolbar"><span id="eg-status">${allNodes.length} 节点 · ${allEdges.length} 关系</span><button class="graph-tool" id="eg-pause">暂停</button><button class="graph-tool" id="eg-reset">重置</button></div><div class="event-graph-stage" id="event-graph"><div class="graph-loading">构建图谱中…</div></div><div id="eg-detail" class="eg-detail"></div></div><div class="drawer-section"><h4>RISK CHAIN NODES</h4><div class="chain-flow">${risk.map(n=>`<span class="chain-chip" style="border-left:3px solid ${typeColor(n.entity_type)}">${esc(n.entity_type)} · ${esc(n.name)}</span>`).join('')||'<span class="empty">暂无风险链实体</span>'}</div></div><div class="drawer-section"><h4>EVIDENCE SIGNALS</h4>${ev.map(x=>`<div class="evidence">${esc(x.evidence_sentence)}<br><small>Source document ${esc(x.source_doc_id)}</small></div>`).join('')||'<div class="empty">暂无证据</div>'}</div>`;renderEventGraph(allNodes,allEdges)}catch(err){$('#event-detail').innerHTML='<div class="empty">事件详情载入失败。</div>'}}
let egState=null;
function renderEventGraph(allNodes,allEdges){
  const limit=60,stage=$('#event-graph'),w=460,h=360;
  const nodeMap=new Map(allNodes.map(n=>[n.id,n]));
  const validEdges=allEdges.filter(e=>nodeMap.has(e.subject_id)&&nodeMap.has(e.object_id));
  const degree=new Map();
  validEdges.forEach(e=>{degree.set(e.subject_id,(degree.get(e.subject_id)||0)+1);degree.set(e.object_id,(degree.get(e.object_id)||0)+1)});
  const topNodes=allNodes.slice().sort((a,b)=>(degree.get(b.id)||0)-(degree.get(a.id)||0)).slice(0,limit);
  const topIds=new Set(topNodes.map(n=>n.id));
  const edges=validEdges.filter(e=>topIds.has(e.subject_id)&&topIds.has(e.object_id));
  const cx=w/2,cy=h/2;
  const nodes=topNodes.map((n,i)=>({...n,x:cx+Math.cos(i*2.399)*(70+(i%5)*22),y:cy+Math.sin(i*2.399)*(55+(i%4)*20),vx:0,vy:0,r:Math.max(4,Math.min(11,4+(degree.get(n.id)||0)*1.2))}));
  const idIdx=new Map(nodes.map((n,i)=>[n.id,i]));
  const links=edges.map(e=>({a:nodes[idIdx.get(e.subject_id)],b:nodes[idIdx.get(e.object_id)],pred:e.predicate}));
  egState={nodes,links,running:true,drag:null,raf:null};
  stage.innerHTML='';
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');
  svg.setAttribute('viewBox',`0 0 ${w} ${h}`);
  svg.setAttribute('preserveAspectRatio','xMidYMid meet');
  svg.innerHTML='<g class="eg-world"><g class="eg-edges"></g><g class="eg-nodes"></g></g>';
  stage.appendChild(svg);
  const egEdges=svg.querySelector('.eg-edges');
  const egNodes=svg.querySelector('.eg-nodes');
  links.forEach((l,i)=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.classList.add('eg-edge');line.dataset.pred=l.pred;line.setAttribute('x1',l.a.x);line.setAttribute('y1',l.a.y);line.setAttribute('x2',l.b.x);line.setAttribute('y2',l.b.y);egEdges.appendChild(line)});
  nodes.forEach(n=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('eg-node');g.dataset.id=n.id;g.innerHTML=`<circle r="${n.r}" fill="${typeColor(n.entity_type)}"/><text x="${n.r+4}" y="3">${esc((n.name||'').slice(0,14))}</text>`;g.addEventListener('click',ev=>{ev.stopPropagation();selectEgNode(n)});g.addEventListener('pointerdown',ev=>startEgDrag(ev,n,g));g.addEventListener('pointerenter',()=>{const t=$('#eg-detail');t.innerHTML=`<strong style="color:${typeColor(n.entity_type)}">${esc(n.entity_type)}</strong> · ${esc(n.name)}<br><small>置信度 ${n.confidence??'—'} · ${(n.source_doc_ids||[]).length} 来源文档</small>`});egNodes.appendChild(g)});
  $('#eg-pause').onclick=()=>{egState.running=!egState.running;$('#eg-pause').textContent=egState.running?'暂停':'继续';if(egState.running)animateEg()};
  $('#eg-reset').onclick=()=>renderEventGraph(allNodes,allEdges);
  animateEg();
}
function animateEg(){if(!egState||!egState.running)return;const ns=egState.nodes,w=460,h=360;for(const n of ns){n.vx+=(230-n.x)*.004;n.vy+=(180-n.y)*.004;n.vx*=.9;n.vy*=.9;n.x+=n.vx;n.y+=n.vy;for(const o of ns){if(n===o)continue;const dx=n.x-o.x,dy=n.y-o.y,d=Math.max(8,Math.hypot(dx,dy));if(d<50){n.vx+=dx/d*(50-d)*.03;n.vy+=dy/d*(50-d)*.03}}}drawEg();egState.raf=requestAnimationFrame(animateEg)}
function drawEg(){if(!egState)return;egState.nodes.forEach(n=>{const el=document.querySelector(`.eg-node[data-id="${CSS.escape(n.id)}"]`);if(el)el.setAttribute('transform',`translate(${n.x},${n.y})`)});document.querySelectorAll('.eg-edge').forEach((el,i)=>{const l=egState.links[i];el.setAttribute('x1',l.a.x);el.setAttribute('y1',l.a.y);el.setAttribute('x2',l.b.x);el.setAttribute('y2',l.b.y)})}
function selectEgNode(node){const neighbors=new Set(egState.links.flatMap(l=>l.a===node?[l.b.id]:l.b===node?[l.a.id]:[]));document.querySelectorAll('.eg-node').forEach(el=>el.classList.toggle('dimmed',el.dataset.id!==node.id&&!neighbors.has(el.dataset.id)));document.querySelectorAll('.eg-edge').forEach((el,i)=>{const l=egState.links[i];el.classList.toggle('highlighted',l.a===node||l.b===node)});const t=$('#eg-detail');const evs=(node.evidence||[]).slice(0,2);t.innerHTML=`<strong style="color:${typeColor(node.entity_type)}">${esc(node.entity_type)}</strong> · ${esc(node.name)}<div class="detail-row"><span>置信度</span><b>${node.confidence??'—'}</b></div><div class="detail-row"><span>来源文档</span><b>${(node.source_doc_ids||[]).length}</b></div>${evs.map(x=>`<div class="evidence">${esc(x.evidence_sentence)}</div>`).join('')}`}
function startEgDrag(ev,node,el){ev.stopPropagation();egState.drag={node,el};el.setPointerCapture(ev.pointerId);egState.running=false}
function moveEgDrag(ev){if(egState&&egState.drag){const r=$('#event-graph').getBoundingClientRect();egState.drag.node.x=(ev.clientX-r.left)/r.width*460;egState.drag.node.y=(ev.clientY-r.top)/r.height*360;drawEg()}}
function endEgDrag(){if(egState)egState.drag=null}
document.addEventListener('pointermove',moveEgDrag);
document.addEventListener('pointerup',endEgDrag);
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawer-backdrop').classList.remove('open')}
document.querySelectorAll('[data-view]').forEach(n=>n.onclick=()=>{state.currentView=n.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===state.currentView));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active-view',x.id===`${state.currentView}-view`));$('#page-title').textContent={overview:'风险知识图谱',events:'事件库',insights:'风险洞察'}[state.currentView]});$('#event-search').oninput=e=>{state.query=e.target.value;renderEvents()};$('#drawer-close').onclick=closeDrawer;$('#drawer-backdrop').onclick=closeDrawer;$('#explore-random').onclick=()=>openEvent(state.events[Math.floor(Math.random()*state.events.length)].id);$('#refresh').onclick=boot;boot();
